version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: nome_do_banco
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d nome_do_banco"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://usuario:senha@postgres:5432/nome_do_banco
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "
      until npx prisma migrate deploy; do
        echo 'Waiting for the database...'
        sleep 5
      done &&
      node dist/server.js
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
